// <auto-generated />
using System;
using DominoPontaDeQuina.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DominoPontaDeQuina.Migrations.Persistence.Migrations
{
    [DbContext(typeof(DominoDbContext))]
    [Migration("20260901060409_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Jogadores", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Lance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("PartidaId", "Timestamp");

                    b.ToTable("Lances", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.ParticipacaoPartida", b =>
                {
                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.HasKey("PartidaId", "JogadorId");

                    b.HasIndex("JogadorId");

                    b.ToTable("ParticipacoesPartida", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PontuacaoAlvo")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Partidas", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Ranking", b =>
                {
                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int");

                    b.HasKey("JogadorId");

                    b.ToTable("Rankings", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Jogador", b =>
                {
                    b.HasOne("DominoPontaDeQuina.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Jogadores")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Lance", b =>
                {
                    b.HasOne("DominoPontaDeQuina.Domain.Entities.Jogador", "Jogador")
                        .WithMany("Lances")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DominoPontaDeQuina.Domain.Entities.Partida", "Partida")
                        .WithMany("Lances")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.ParticipacaoPartida", b =>
                {
                    b.HasOne("DominoPontaDeQuina.Domain.Entities.Jogador", "Jogador")
                        .WithMany("Participacoes")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DominoPontaDeQuina.Domain.Entities.Partida", "Partida")
                        .WithMany("Participacoes")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Ranking", b =>
                {
                    b.HasOne("DominoPontaDeQuina.Domain.Entities.Jogador", "Jogador")
                        .WithOne("Ranking")
                        .HasForeignKey("DominoPontaDeQuina.Domain.Entities.Ranking", "JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Jogador", b =>
                {
                    b.Navigation("Lances");

                    b.Navigation("Participacoes");

                    b.Navigation("Ranking");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Partida", b =>
                {
                    b.Navigation("Lances");

                    b.Navigation("Participacoes");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Jogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
